version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    volumes:
      - ./common/media/:/app/common/media/
    tmpfs:
      - /mnt/ramdisk:uid=1000,gid=1000,mode=1777,size=4G
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./common/media:/var/www/common/media
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email contact@kanjiru.co --agree-tos --no-eff-email --staging -d app.kanjiru.co  -d www.app.kanjiru.co

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/micheldrucker/appKanjiruLive/public/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/micheldrucker/appKanjiruLive/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
